name: Nest.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Nest.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: false
          always-auth: false

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "PORT=4000" > .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=trackbalance" >> .env

      - name: Build the project
        run: npm run build

      - name: Stop current PM2 process by name
        run: pm2 stop track_balance || true

      - name: Stop current PM2 process by name
        run: pm2 restart track_balance || true

      - name: Save PM2 process list
        run: pm2 save